### ISSUE TITLE
save to specific name

### ISSUE THREAD

**Issue by EricW123** [buguniao55555/factorio_server_controller#4]
`!!save file_name` should save the current file to a file called file_name.zip or similar thing.
`!!ls ?` should also print the file name if the file was saved in this method.
example: `1: 2024-04-09 13:00:12 before_ForgeHammer by EricW123`
`!!ls x` should: if x is numeric, then load the x-th latest file; else, try to load the file named `x`, print error if such file not exists.

**Comment by buguniao55555** [comment]
Done
